title: Congress 2020
description: >-
  A short description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - create_entries.py
  - _config.example.yml
  - screenshot.png

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: 
      enable: true
      default_zoom: 17
      home_coord: 47.37808, 8.53935
      map_provider: "OpenStreetMap.Mapnik"
      markers:
        - icon: "comments"  # https://fontawesome.com/icons?from=io
          coord: 47.37808, 8.53935
          marker_color: "red"
          icon_color: "white"
          description: >-
            A short description

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
